### ISSUE TITLE
Could not find 'force_directed' or 'X_force_directed' in .obsm"

### ISSUE THREAD

**Issue by aluxsn** [theislab/cellrank#1084] opened 2023-07-10 10:20 UTC
i want an issue to solve this problem : KeyError: "Could not find 'force_directed' or 'X_force_directed' in .obsm"
...

```python
sc.pl.embedding(adata, basis="force_directed", color="cell_type")
```
![Screenshot from 2023-07-10 12-19-39](https://github.com/theislab/cellrank/assets/83249155/14442080-2d1f-4a92-8ec6-eb1d093800f3)

```pytb
KeyError: "Could not find 'force_directed' or 'X_force_directed' in .obsm"
...
```

#### Versions:

scanpy==1.9.3 anndata==0.8.0 umap==0.5.3 numpy==1.23.5 scipy==1.9.1 pandas==1.3.5 scikit-learn==1.2.2 statsmodels==0.13.5 python-igraph==0.10.4 louvain==0.8.0 pynndescent==0.5.8
> ...

**Comment by Marius1311** [comment] 2023-07-11 09:49
Hi @aluxsn, I need some more context to be able to help you here. I cannot see the screenshot, your versions do not include the CellRank version you used, and I'm not sure what you were trying to do. It looks like the error tells you what the problem is: you haven't computed the embedding you are trying to visualize.

**Comment by michalk8** [comment] 2023-08-16 13:59
There seems to be no embedding in `adata.obsm['X_force_directed']` or `adata.obsm['force_directed']`. Please check the possible values for `basis=...` using `print(adata.obsm.keys())`; closing this.

**Closed by michalk8** 2023-08-16 13:59 UTC
Labels: bug
