### ISSUE TITLE
Return p-values for lineage driver genes

### ISSUE THREAD

**Issue by cdedonno** [theislab/cellrank#432] opened 2020-10-14 10:31 UTC
Hey guys, 

as I have already discussed with @Marius1311, it would be very useful to have p-values associated with the correlation scores returned for genes identified as lineage drivers. If I understand correctly, these are found by computing a rank correlation between their expression and the fate probabilities. I think a permutation test, or bootstrapping, could be some viable solutions for this.

**Comment by Marius1311** [comment] 2020-10-15 06:49
Hi Carlo! Thanks for opening the issue. A permutation test for the gene correlations would indeed be one possibility, and probably the easiest. 

The alternative would be to do trade-seq-like testing, see https://www.nature.com/articles/s41467-020-14766-3. Their testing is based on GAMs - since we also fit GAMs, we could do just the same thing. The propose a number of different tests in their paper (i.e. find any gene which displays non-random dynamics, find genes that display different dynamics between lineages, find gene that are upregulated towards the end, ...). It would be great if you could have a brief look at this paper to let me know which of these tests you're interested in to solve your biological question.

**Comment by cdedonno** [comment] 2020-10-15 07:59
Hi Marius, 

I have read the paper. tradeSeq of course seems to give more room for different kinds of tests and might be a better solution in general. In my particular case both within and between lineage tests would be useful. I want to test the genes associated with two lineages, and at the same time check if the genes are differentially expressed between them.

**Comment by cdedonno** [comment] 2020-10-15 10:50
Hi again, if you are using Spearman correlation, there is no need to actually make a permutation test. You have an analytic solution for the p-value, you can check this on the [wikipedia entry](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient#Determining_significance).

**Comment by michalk8** [comment] 2020-10-15 13:07
Hi @cdedonno ,
we're actually using Pearson correlation, I've implemented the p-values according to https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Testing_using_Student's_t-distribution
I've also added 95% confidence intervals for the correlations from https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Using_the_Fisher_transformation
I still need to write tests but I did some sanity checks and it seems to be fine. Would you mind checking this out?
Note that pvalues and CIs are not save in `adata` object, so if you're using the estimator, you have to specify ``return_genes=True``.

**Comment by Marius1311** [comment] 2020-10-16 07:08
Hi @cdedonno , please bear with us, we will need a couple of days before we can get back to this.

**Comment by Marius1311** [comment] 2020-10-16 07:08
We have it on our radar though.

**Comment by Marius1311** [comment] 2020-10-20 09:20
Hi @cdedonno , we're back onto this! See #437 for the discussion. We're computing CI's on pearson correlation values and we're including a FDR correction. However, this is untested so please do test this and get back to @michalk8 who is taking care of this.

**Comment by Marius1311** [comment] 2020-11-09 09:20
Hi @cdedonno, this is done, the current version of master allows you to compute p-values!

**Comment by Marius1311** [comment] 2020-11-09 09:20
Would be great to hear your feedback on this.

**Comment by cdedonno** [comment] 2020-11-09 09:41
Hi @Marius1311, I have seen you added this feature. Still haven't had the time to try it out yet. Will give you some feedback as soon as I get to work with it.

**Comment by Marius1311** [comment] 2020-11-09 10:28
thanks!

**Comment by Marius1311** [comment] 2020-11-23 09:32
I'm closing this as I'm assuming the issue is closed in our latest release.

**Closed by Marius1311** 2020-11-23 09:32 UTC
Labels: enhancement
