### ISSUE TITLE
Functsions related to Expression Trend not working

### ISSUE THREAD

**Issue by JyoRoy21** [theislab/cellrank#1207] opened 2024-07-03 20:45 UTC
I am running the tutorial code for CellRank and came across an error while running the functions for trend expression, Can you please help me with the same
Code:
```python
cr.pl.heatmap(
    adata,
    model=model,
    data_key="MAGIC_imputed_data",
    genes=["GATA1", "CD34", "IRF8", "MPO"],
    lineages=["Mono_1_1", "Mega", "CLP"],
    time_key="palantir_pseudotime",
    cbar=False,
    show_all_genes=True,
)
```

Error Output:
```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cellrank/models/_base_model.py](https://localhost:8080/#) in wrapper(wrapped, instance, args, kwargs)
     63                     instance.reraise()
---> 64                 return wrapped(*args, **kwargs)
     65             except Exception as e:  # noqa: BLE001

11 frames
AttributeError: 'DataFrame' object has no attribute 'iteritems'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cellrank/models/_base_model.py](https://localhost:8080/#) in reraise(self)
   1231         """Raise the original exception with additional model information."""
   1232         # retain the exception type and also the original exception
-> 1233         raise type(self._exc)(f"Fatal model failure `{self}`.") from self._exc
   1234 
   1235     def _get_colors(

AttributeError: Fatal model failure `<FailedModel[origin=GAMR[gene='GATA1', lineage='Mono_1_1', model=None]]>`.
```

Versions:
cellrank==2.0.5.dev1+g6074913 scanpy==1.10.2 anndata==0.10.8 numpy==1.25.2 numba==0.58.1 scipy==1.11.4 pandas==2.0.3 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.2 scvelo==0.3.2 pygam==0.9.1 matplotlib==3.7.1 seaborn==0.13.1

**Comment by michalk8** [comment] 2024-08-04 22:22
Hi @JyoRoy21 , could you please post the full traceback?
I haven't been able to find `iteritems` in our codebase, must be one of the dependencies.

**Comment by WeilerP** [comment] 2024-12-19 13:42
I'll close the issue as the issue doesn't seem to be caused by CellRank.

**Closed by WeilerP** 2024-12-19 13:42 UTC
Labels: bug
