### ISSUE TITLE
Saving figures generated by ScVelo and CellRank

### ISSUE THREAD

**Issue by jwalewski** [theislab/cellrank#1124] opened 2023-09-20 21:01 UTC
Hello,

I am wondering how it's possible to save the data (and the graphs) generated by scvelo and cellrank.

More specifically, I am using both programs on a cluster, and I am running them inside of a shell script (for ease of automation). It seems the underlying dependencies such as matplotlib have methods such as "savefigure()"... has such a method been implemented for your programs?

Thanks for helping me out!

**Comment by Marius1311** [comment] 2023-09-21 14:40
Hi @jwalewski, yes, many (if not all) cellrank plotting methods have a `save` parameter, where you can pass a filepath to write the saved figure. See e.g. https://cellrank.readthedocs.io/en/latest/api/_autosummary/estimators/cellrank.estimators.GPCCA.html#cellrank.estimators.GPCCA.plot_coarse_T

**Comment by jwalewski** [comment] 2023-09-21 16:10
Understood, and I have done that now, but I still run into an issue where even if I specify a path name (and a pathname as absolute as /~/) the program is concatenating figues/tsne/ in front, and therefore my shell is giving a directory not found error.

Here's my code:

```
#1. Import Packages
import sys
import cellrank as cr
import scanpy as sc
import warnings

#2. Configuring basic packages
sc.settings.set_figure_params(frameon=False, dpi=100)
cr.settings.verbosity = 2
warnings.simplefilter("ignore", category=UserWarning)

#3. Testing data
adata = cr.datasets.bone_marrow()
adata

#4. Preprocessing
adata = adata[:, adata.var["palantir"]].copy()
adata.layers["MAGIC_imputed_data"] = adata.obsm["MAGIC_imputed_data"].copy()

sc.pp.filter_genes(adata, min_cells=5)
sc.pp.normalize_total(adata, target_sum=1e4)

sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata, n_top_genes=3000)

#5. Data analysis
sc.tl.pca(adata, random_state=0)
sc.pp.neighbors(adata, random_state=0)

sc.pl.embedding(adata, basis="tsne", color=["clusters", "palantir_pseudotime"], save="/~/TEST")
```

Here's the error:
```
WARNING: saving figure to file figures/tsne/~/TEST.pdf
Traceback (most recent call last):
  File "<string>", line 31, in <module>
  File "/home/jw2894/.local/lib/python3.8/site-packages/scanpy/plotting/_tools/scatterplots.py", line 458, in embedding
    _utils.savefig_or_show(basis, show=show, save=save)
  File "/home/jw2894/.local/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 311, in savefig_or_show
    savefig(writekey, dpi=dpi, ext=ext)
  File "/home/jw2894/.local/lib/python3.8/site-packages/scanpy/plotting/_utils.py", line 287, in savefig
    pl.savefig(filename, dpi=dpi, bbox_inches='tight')
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 2808, in print_pdf
    file = PdfFile(filename, metadata=metadata)
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/backends/backend_pdf.py", line 713, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
  File "/home/jw2894/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 489, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'figures/tsne/~/TEST.pdf'
```

Any idea of how to disable this?

**Comment by Marius1311** [comment] 2023-09-22 11:59
Hi @jwalewski, are you sure you're on the most recent version of CellRank? I recall we had this issue somewhere and we decided to disable this behaviour. Can you remember this @michalk8 ?

**Comment by michalk8** [comment] 2023-09-22 12:03
> sc.pl.embedding(adata, basis="tsne", color=["clusters", "palantir_pseudotime"], save="/~/TEST")

The problem is passing `save="/~/TEST"`, would just use `save="TEST"` and not start with `/` or use `~`, since it seems `scvelo` doesn't expand user's home directory.

**Comment by jwalewski** [comment] 2023-09-22 14:39
This would be line 54 of scvelo.settings (https://github.com/theislab/scvelo/blob/master/scvelo/settings.py), correct? And if so, I think this behavior of ignoring the /, ~, and other special characters may still be considered a bug given that the default prefix is written as ```./figures/``` - This would be fine as then the user could cd to wherever they're like scvelo to generate figures, but since the ```./``` is getting eliminated the pathname is, as stated in the "no such file or directory" error message, ```figures/[user specified name]```, which causes the error. 

Also, I tried editing the default filepath in my scvelo installation - but when I run my script that calls cellrank, the error didn't update at all. I am wondering if this is because I installed scvelo before cellrank, and then cellrank installed another version of scvelo? I've tried checking for a second installation but I can't find it. 

Let me know what you guys think.

**Comment by jwalewski** [comment] 2023-09-28 14:48
I believe after some digging that I've found a solution. However, it's not the most elegant way of doing things:

by altering line 78 of _settings.py of scanpy to ```        figdir: Union[str, Path] = "",  ``` I can eliminate the ./figures/ in front of the path. Then, by inserting a line in between 457 and 458 of scanpy/plotting/_tools/scatterplots.py which reassigns basis to an empty string,    ``` basis = ""```, it becomes possible to remove all of the directory generated before the user's input and I finally got a graph saved.

However, I get this isn't the most ideal workaround since these are modifications to a cellrank dependency as compared to cellrank itself. In the meantime, though, it _seems_ to work.

**Comment by michalk8** [comment] 2023-09-28 16:44
If only creating new directories is the issue (because of e.g., permsissions), easiest would be to set `sc.settings.figdir = ""` as below:

```python
import scanpy as sc

sc.settings.figdir = ""

adata = sc.datasets.blobs()
sc.pp.pca(adata)

sc.pl.pca(adata, save="foo.pdf")  # will save to `./pcafoo.pdf`
```

However, I agree that the filename is always modified by scanpy [here](https://github.com/scverse/scanpy/blob/master/scanpy/plotting/_utils.py#L311) and I think this shouldn't be the default behaviour (rather opt-in). Would suggest to open an issue there!

**Comment by michalk8** [comment] 2023-11-02 23:05
> I don't think cellrank should have this behavior by default either

Fully agree, though in the `scanpy`/`scvelo` side, this would require to
On our side, slightly modifying [save_fig](https://github.com/theislab/cellrank/blob/01a79ca94d5a297b0e9fc6ded9e3d0e951fd2de6/src/cellrank/_utils/_utils.py#L820) by changing defaults/using `settings.figdir` when the path is not absolute should do it.

Unfortunately, I won't have the capacity to look at it now, but if you're interested, any contribution is welcome!

**Comment by Marius1311** [comment] 2024-04-19 14:02
Closing this, feel free to reopen if the issues persists.

**Closed by Marius1311** 2024-04-19 14:02 UTC
Labels: enhancement
