### ISSUE TITLE
Show cellrank and scvelo commit hashs when printing versions in cellrank

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#435] opened 2020-10-15 08:58 UTC
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

When calling `cr.logging.print_versions()`, I already get the commit hash for scvelo printed, but not for cellrank. Would be important for reproducibility.

**Comment by Marius1311** [comment] 2020-10-15 19:42
Amazing, thanks.

**Comment by Marius1311** [comment] 2020-10-15 20:39
I'm just checking this out. I pulled from master and I display the commit hash in a jupyter notebook. It gives me `c34083d`, but the most recent commit on master is `b3e00a8`. Actually, this does not make sense because you only introduced full commit hash printing in a later commit, so I must be at last at this later commit. What's going on?

**Comment by michalk8** [comment] 2020-10-16 07:16
Did you pip install it? Mine says `'1.0.0-rc.12+gb3e00a8'`.

**Comment by Marius1311** [comment] 2020-10-16 09:29
No, I didn't pip install it, I cloned the repo, run
```
pip install -e '.[dev]'
python-vendorize
```
imported it into a jupyter notebook and printed the versions.

**Comment by michalk8** [comment] 2020-10-16 10:13
I just did the same and can't reproduce it, i.e. I'm getting:
```
Running CellRank 1.0.0-rc.12+gb3e00a8, on 2020-10-16 12:12.
```
and
```
cellrank==1.0.0-rc.12+gb3e00a8 scanpy==1.6.0 anndata==0.7.4 numpy==1.19.2 numba==0.51.2 scipy==1.5.2 pandas==1.1.3 scikit-learn==0.23.2 statsmodels==0.12.0 python-igraph==0.8.3 scvelo==0.2.3.dev26+g8351f46 pygam==0.8.0 matplotlib==3.3.2 seaborn==0.11.0
```
Please check if you're using the right jupyter kernel.

**Comment by Marius1311** [comment] 2020-10-16 14:10
ok, let me check.

**Comment by Marius1311** [comment] 2020-10-16 14:15
weird, I'm definitely using the right kernel, and I still get the same result. I set up my kernel using `ipykernel`, if that helps.

**Comment by michalk8** [comment] 2020-10-16 18:26
I've tested this, the commit is always as when you've installed it. I don't believe this is a bug and I can't/don't want to change this. Closing this.

**Closed by michalk8** 2020-10-16 18:26 UTC
Labels: enhancement
