### ISSUE TITLE
Kernel dies when calling `cr.pl.heatmap`

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#279] opened 2020-07-23 07:56 UTC
I don't think this is specific to the heatmap plotting function, I think it has something to do with MPI or rpy2. When I call `cr.pl.heatmap`, I get the below

```pytb
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: likely location of problem given in stack below
[0]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
[0]PETSC ERROR:       INSTEAD the line number of the start of the function
[0]PETSC ERROR:       is given.
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
system msg for write_line failure : Bad file descriptor
[I 09:47:15.074 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel a0483e5f-0e79-4209-af8e-6a713a99d689 restarted
Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 552, in initialize
    self.init_sockets()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[I 09:47:18.085 LabApp] KernelRestarter: restarting kernel (2/5), keep random ports
kernel a0483e5f-0e79-4209-af8e-6a713a99d689 restarted
Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 552, in initialize
    self.init_sockets()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[I 09:47:21.099 LabApp] KernelRestarter: restarting kernel (3/5), keep random ports
kernel a0483e5f-0e79-4209-af8e-6a713a99d689 restarted
Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 552, in initialize
    self.init_sockets()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[I 09:47:24.111 LabApp] KernelRestarter: restarting kernel (4/5), keep random ports
kernel a0483e5f-0e79-4209-af8e-6a713a99d689 restarted
Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 552, in initialize
    self.init_sockets()
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
[W 09:47:27.125 LabApp] KernelRestarter: restart failed
[W 09:47:27.125 LabApp] Kernel a0483e5f-0e79-4209-af8e-6a713a99d689 died, removing from map.
kernel a0483e5f-0e79-4209-af8e-6a713a99d689 restarted failed!
```

This happened when I started a jupyter lab from my base conda environment. Note that neither mpi nor PETSc nor rpy2 are installed in my base environment. However, I thought this should not matter as the notebook itself uses a kernel based on an environment which has all of these installed. Anyways, when I shut down the jupyter lab and start it again, but this time from another conda environment where mpi and PETSc are installed, then I don't get the above error and everything works. Weird, isn't it?

#### Versions:
cellrank==1.0.0-rc.0 scanpy==1.5.1 anndata==0.7.3 numpy==1.18.5 scipy==1.4.1 pandas==1.0.5 scikit-learn==0.22 statsmodels==0.10.2 python-igraph==0.7.1 scvelo==0.2.2.dev51+ga7de78a
> ...

**Comment by michalk8** [comment] 2020-07-31 19:42
I have sometimes problems with `multiprocessing` backend not willing to close. Regarding the above error,
I still can't replicate it, the only one, apart from the backend hanging, was
```pytb
Error: C stack usage  139189340036 is too close to the limit
Error: C stack usage  139189340084 is too close to the limit
Error: C stack usage  139189340084 is too close to the limit
Error: C stack usage  139189339572 is too close to the limit
Fatal error: unable to initialize the JIT

[I 11:11:42.179 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 74f398bd-d702-4260-8a7d-f2c2710a0643 restarted
Traceback (most recent call last):
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 567, in initialize
    self.init_sockets()
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in us
```

I really need to investigate why the backend doesn't close, since it's been happening a lot lately.

**Comment by michalk8** [comment] 2020-08-09 10:44
I'm unable to reproduce this, closing this until it resurfaces again.

**Closed by michalk8** 2020-08-09 10:44 UTC
Labels: bug
