### ISSUE TITLE
cellrank.estimators.GPCCA.compute_lineage_drivers if subset on clusters, confidence intervals are NaN- is this expected behavior?

### ISSUE THREAD

**Issue by JenniferWUSTL** [theislab/cellrank#1021] opened 2023-04-05 15:54 UTC
Good morning! Apologies for so many questions recently.  I just have a quick question, when running `cellrank.estimators.GPCCA.compute_lineage_drivers`, I get confidence intervals returned if I only specify for example `lineages = ['3', '4', '5']`, but if I pass `lineages = ['3', '4', '5'], cluster_key = 'leiden', clusters = ['0', '1', '2', '3', '4', '5']`, I receive NaN for confidence intervals. I don't need the confidence intervals for what I am doing, but just wanted to post to see if this is expected behavior or a bug.  Happy to post more code if that will be helpful.  Thank you for your work!
...

**Comment by Marius1311** [comment] 2023-04-05 17:12
Hi @JenniferWUSTL, I think that's a bug! I don't see why we wouldn't be able to compute the confidence intervals on a subset of the data. Do you know more here @michalk8 ?

**Comment by michalk8** [comment] 2023-04-13 21:53
> I receive NaN for confidence intervals

Is it only for the CI, or the whole row (including the correlation value, etc.). If the whole row, it can be expected, since NaN values should only happen when the gene expression in the selected clusters is constant (e.g., `0`); you can use the below snippet to check if the values are all 0s (or any other constant):

```python
adata = g.adata  # g is the estimator, adata is the one from cr.datasets.pancreas()
clusters = ["Ngn3 low EP"]
subset = adata[adata.obs['clusters'].isin(clusters), 'Rragb']
subset.X  # all 0s, in the drivers, it has NaN correlation
```

**Comment by JenniferWUSTL** [comment] 2023-04-13 21:59
Hi @michalk8 ! I receive it only for confidence intervals, not the correlations or p-values, etc.

**Comment by michalk8** [comment] 2023-04-13 22:07
> Hi @michalk8 ! I receive it only for confidence intervals, not the correlations or p-values, etc.

Then this seems like a bug indeed. If you can share with us some way to replicate this, it would be great.

**Comment by JenniferWUSTL** [comment] 2023-04-14 17:07
Hi @michalk8 ! I tried to reproduce this using `cr.datasets.reprogramming_schiebinger()` ;however, I cannot reproduce this with that dataset. I can reproduce it on my dataset with:

```
 drivers = b.compute_lineage_drivers(lineages = ['4_2', '5', '6', '3_2', '0'])
drivers
         4_2_corr  4_2_pval  4_2_qval  4_2_ci_low  4_2_ci_high    
PLAU     0.536961       0.0       0.0    0.524940     0.548768
```

and then:
```
drivers = b.compute_lineage_drivers(lineages = ['4_2', '5', '6', '3_2', '0'], cluster_key = 'leiden', clusters = ['0', '1', '2', '3', '4', '5', '6', '7', '10', '11', '12', '8'])`
drivers
         4_2_corr  4_2_pval  4_2_qval  4_2_ci_low  4_2_ci_high    
PLAU     0.544179       0.0       0.0         NaN          NaN 
```

I checked the correlations on my data and they all fall within +/- 1, and looking through the code I found here (https://github.com/theislab/cellrank/blob/e54987b800a2a85f94c735ef0e9a33a4736f2e00/cellrank/_utils/_utils.py#L392) I can't seem to find why it shouldn't return confidence intervals but still compute the other values- in this case, I have no confidence intervals for any of my genes. I'm not using these downstream in my analysis, but I do wonder if I should be cautious about interpreting the results since these are not returned. What do you suggest for troubleshooting?

If it's helpful my data was processed as following the scanpy tutorial with normalized counts in `adata.X` and then I proceeded with the following code, prior to running `compute_lineage_drivers` as above: 
```
adata.layers["spliced"] = adata.X
adata.layers["unspliced"] = adata.X
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
wk = WOTKernel(adata, time_key = 'time')
wk.compute_initial_growth_rates(organism = 'human', key_added = "growth_rate_init")
wk.compute_transition_matrix(growth_iters=3, growth_rate_key="growth_rate_init", self_transitions="connectivities")
cn = ConnectivityKernel(adata).compute_transition_matrix()
ck1 = 0.9*wk + 0.1*cn
b = cr.estimators.GPCCA(ck1)
b
b.compute_schur(n_components = 20)
```
`b.compute_macrostates(n_states = 13, cluster_key = 'leiden')` 
```
b.set_terminal_states(["9", "8", "3_2", "0"])
b.compute_absorption_probabilities()
```

Thank you for your time, and sorry I don't have a reproducible dataset to share at this time!

**Comment by JenniferWUSTL** [comment] 2023-04-14 18:21
To follow-up, if I use `method = 'perm_test'` instead of the default 'fisher', confidence intervals are returned with my dataset.

**Comment by michalk8** [comment] 2023-04-14 19:17
> I checked the correlations on my data and they all fall within +/- 1, and looking through the code I found here (

That's strange, I ran the code manually for the correlation value of `PLAU`, it shouldn't be NaN. It's later assigned to the final DataFrame [here](https://github.com/theislab/cellrank/blob/master/cellrank/_utils/_utils.py#L468-L469), could you please print out whether before/after assignment the CI values are NaN? I suspect
Also, if you're not using the latest version (from `master`), can you please update it + post your `pandas/numpy` versions?

The other thing that can maybe cause this is the subset by clustering which happens [here](https://github.com/theislab/cellrank/blob/e54987b800a2a85f94c735ef0e9a33a4736f2e00/cellrank/estimators/mixins/_lineage_drivers.py#L169-L170); the simplest way to check is to pass all the `clusters` and see whether all the values are the same as not passing the clusters (they should).

**Comment by JenniferWUSTL** [comment] 2023-04-14 19:33
Thanks @michalk8 , how do you suggest I do this? _It's later assigned to the final DataFrame [here](https://github.com/theislab/cellrank/blob/master/cellrank/_utils/_utils.py#L468-L469), could you please print out whether before/after assignment the CI values are NaN?_

I think this is the most up to date version, but please let me know if I'm wrong and I'm happy to update: 
```
cr.logging.print_versions()
cellrank==1.5.1+gd7f499c0 scanpy==1.9.2 anndata==0.8.0 numpy==1.23.5 numba==0.56.4 scipy==1.9.3 pandas==1.5.3 pygpcca==1.0.4 scikit-learn==1.2.0rc1 statsmodels==0.13.5 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.6.2 seaborn==0.12.2
```


By visual inspection, the correlations are the same with 
```
mine.compute_lineage_drivers(lineages = ['4_2', '5', '6', '3_2', '0'], cluster_key = 'leiden', clusters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']) 

PLAU   -0.482829     0.0     0.0       NaN        NaN 
```

and  
```
mine.compute_lineage_drivers(lineages = ['4_2', '5', '6', '3_2', '0'])

PLAU   -0.482829     0.0     0.0 -0.495563  -0.469887
```  
where I have 13 clusters (0 through 12, so should not be subsetting.

I can check if all values are the same though, just need to figure out how :) 

Also, I misspoke about method = 'perm_test', there are still some CIs that are NaN with q-values/p-values not NaN, but it's no longer every entry like is for "fisher", sorry for any confusion!

**Comment by Marius1311** [comment] 2023-09-14 14:10
Hi @michalk8, is there anything to do here, or can we close this?

**Comment by michalk8** [comment] 2023-11-02 23:14
I haven't been able to find a reason why this happens. The one thing I could thought of was that `n - 3` was negative, but in this case the p-value would also be NaN, which is not the case.

The other thing is the subsetting (using a view [here](https://github.com/theislab/cellrank/blob/main/src/cellrank/estimators/mixins/_lineage_drivers.py#L161); maybe copying it would solve, but doesn't make much sense that this would affect the results).

Due to the lack of reproducibility/inactivity, am closing this as unresolved.

**Closed by michalk8** 2023-11-02 23:14 UTC
Labels: bug, question
