### ISSUE TITLE
saving results fails

### ISSUE THREAD

**Issue by stela2502** [theislab/cellrank#797] opened 2022-01-21 14:55 UTC
The adata file from the tutorial https://cellrank.readthedocs.io/en/stable/cellrank_basics.html can not be saved using adata.write('CellRank_Tutorial.h5ad'). 

```python
## after the tutorial https://cellrank.readthedocs.io/en/stable/cellrank_basics.html
adata.write('CellRank_Tutorial.h5ad')
...
```

```pytb

adata.write('CellRank_Tutorial.h5ad')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/utils.py", line 209, in func_wrapper
    return func(elem, key, val, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 148, in write_not_implemented
    raise NotImplementedError(
NotImplementedError: Failed to write value for uns/coarse_fwd, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/anndata/_core/anndata.py", line 1912, in write_h5ad
    _write_h5ad(
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 118, in write_h5ad
    write_attribute(f, "uns", adata.uns, dataset_kwargs=dataset_kwargs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 294, in write_mapping
    write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 130, in write_attribute_h5ad
    _write_method(type(value))(f, key, value, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/utils.py", line 212, in func_wrapper
    raise type(e)(
NotImplementedError: Failed to write value for uns/coarse_fwd, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.

Above error raised while writing key 'uns/coarse_fwd' of <class 'h5py._hl.files.File'> from /.
...
```

#### Versions:

> 
cellrank==1.5.1 scanpy==1.7.2 anndata==0.7.8 numpy==1.21.2 numba==0.55.0 scipy==1.7.3 pandas==1.3.5 pygpcca==1.0.3 scikit-learn==1.0.2 statsmodels==0.13.1 python-igraph==0.8.3 scvelo==0.2.4 pygam==0.8.0 matplotlib==3.5.1 seaborn==0.11.2

**Comment by michalk8** [comment] 2022-01-21 18:53
Hi @stela2502 ,

thanks for raising this issue, can reproduce. Quickest way to fix this is to upgrade to the newest version of `AnnData` as `pip install git+https://github.com/theislab/anndata`, though new release should be coming out soon.
Not sure exactly why I've decided to store the coarse-grained transtions as `AnnData` (could be just `pandas.DataFrame`), so will change it later.

**Comment by stela2502** [comment] 2022-01-24 07:29
Sometimes one is totally focused on an other mechanistic part and just happy there is a structure to store the results in that one does not need to maintain oneself ;-)
But the fact you never tried to save the results seams to be surprising to me. You do not think the results are worth saving?
:-D
Looking forward to the update. At the moment I just deleted the 'problematic' part.

**Comment by Marius1311** [comment] 2022-01-24 09:39
Hi @stela2502, thanks for catching this! 

In my analysis workflow, I usually don't write entire AnnData objects to file to save intermediate results because it's quite memory inefficient. Instead, @michalk8 developed a simple scanpy extension called `scachepy`: https://github.com/theislab/scachepy

As a disclaimer, it's not actively maintained and a bit unstable. Nevertheless, the idea is great: you initialize a cache object `c` before you start your analysis and you tell it where to write the cache to. This object has wrappers for some expensive computations, like scVelo's dynamical model paramter fit. Instead of `scv.tl.recover_dynamics`, you simply call `c.tl.recover_dynamics`, and this automatically writes the results to file. You don't need to worry about filepaths etc every single time you do this, they have been declared once at the beginning of your analysis. This ensures that only those attributes are written to file which are associated with a specific action, which is much more memory efficient. Also, I find this solution more elegant rather than writing to AnnData at intermediate analysis steps.

**Comment by stela2502** [comment] 2022-01-24 09:45
Thank you for this info. 
I saved the adata object at the end of the tutorial analysis as that was as far as I wanted to go there.
We are thinking of how to show the results in VR: https://www.cellexalvr.med.lu.se/

**Comment by Marius1311** [comment] 2022-01-24 14:23
> Thank you for this info. I saved the adata object at the end of the tutorial analysis as that was as far as I wanted to go there. We are thinking of how to show the results in VR: https://www.cellexalvr.med.lu.se/

Nice! Would be very cool to see CellRank results in VR :)

**Comment by stela2502** [comment] 2022-01-27 15:24
To import CellRank results into VR one needs to hop through some loops at the moment.
We can only use the CellRank results as FACS index values. And we can not directly show these values on the umap, but one can create FACS 3D plots and select from there.

**Comment by Marius1311** [comment] 2022-02-09 19:06
Hi @stela2502, sorry but I don't get the problem. Could you give a concrete example of what's currently failing/missing please?

**Comment by Marius1311** [comment] 2022-03-04 02:58
@michalk8, anything to be done here from our side?

**Comment by kmh005** [comment] 2022-03-11 20:28
Hi,
I have been working through the scvelo ->cellrank paga directed graphs workflow, and have tried to save the adata with `adata.write` . Data has saved successfully up until this workflow. As per suggestion above, I upgraded to `anndata @ git+https://github.com/theislab/anndata@8cc6ddc1fb6df0523482b3184aca461c57e93f99`  with `cellrank 1.5.1` and `scvelo 0.2.4`.
I get roughly the same error, `NotImplementedError: Failed to write value for uns/coarse_fwd, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.`.
Any help or tips would be greatly appreciated!

```
adata.write("scvelo.cr.5.h5ad")
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/utils.py:209, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    208 try:
--> 209     return func(elem, key, val, *args, **kwargs)
    210 except Exception as e:

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:148, in write_not_implemented(f, key, value, dataset_kwargs)
    143 @report_write_key_on_error
    144 def write_not_implemented(f, key, value, dataset_kwargs=MappingProxyType({})):
    145     # If it’s not an array, try and make it an array. If that fails, pickle it.
    146     # Maybe rethink that, maybe this should just pickle,
    147     # and have explicit implementations for everything else
--> 148     raise NotImplementedError(
    149         f"Failed to write value for {key}, "
    150         f"since a writer for type {type(value)} has not been implemented yet."
    151     )

NotImplementedError: Failed to write value for uns/coarse_fwd, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
Input In [40], in <cell line: 2>()
      1 import anndata
----> 2 adata.write("scvelo.cr.5.h5ad")

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_core/anndata.py:1912, in AnnData.write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1909 if filename is None:
   1910     filename = self.filename
-> 1912 _write_h5ad(
   1913     Path(filename),
   1914     self,
   1915     compression=compression,
   1916     compression_opts=compression_opts,
   1917     force_dense=force_dense,
   1918     as_dense=as_dense,
   1919 )
   1921 if self.isbacked:
   1922     self.file.filename = filename

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:118, in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
    116 write_attribute(f, "varp", adata.varp, dataset_kwargs=dataset_kwargs)
    117 write_attribute(f, "layers", adata.layers, dataset_kwargs=dataset_kwargs)
--> 118 write_attribute(f, "uns", adata.uns, dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/functools.py:888, in singledispatch.<locals>.wrapper(*args, **kw)
    884 if not args:
    885     raise TypeError(f'{funcname} requires at least '
    886                     '1 positional argument')
--> 888 return dispatch(args[0].__class__)(*args, **kw)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:130, in write_attribute_h5ad(f, key, value, *args, **kwargs)
    128 if key in f:
    129     del f[key]
--> 130 _write_method(type(value))(f, key, value, *args, **kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:294, in write_mapping(f, key, value, dataset_kwargs)
    292 def write_mapping(f, key, value, dataset_kwargs=MappingProxyType({})):
    293     for sub_key, sub_value in value.items():
--> 294         write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/functools.py:888, in singledispatch.<locals>.wrapper(*args, **kw)
    884 if not args:
    885     raise TypeError(f'{funcname} requires at least '
    886                     '1 positional argument')
--> 888 return dispatch(args[0].__class__)(*args, **kw)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:130, in write_attribute_h5ad(f, key, value, *args, **kwargs)
    128 if key in f:
    129     del f[key]
--> 130 _write_method(type(value))(f, key, value, *args, **kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/utils.py:212, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    210 except Exception as e:
    211     parent = _get_parent(elem)
--> 212     raise type(e)(
    213         f"{e}\n\n"
    214         f"Above error raised while writing key {key!r} of {type(elem)}"
    215         f" from {parent}."
    216     ) from e

NotImplementedError: Failed to write value for uns/coarse_fwd, since a writer for type <class 'anndata._core.anndata.AnnData'> has not been implemented yet.

Above error raised while writing key 'uns/coarse_fwd' of <class 'h5py._hl.files.File'> from /.
```

**Comment by Marius1311** [comment] 2022-03-17 11:10
@michalk8, it seems like we write an AnnData object to AnnData.uns, do we really want to do this? @ivirshup asked me that recently as well.

**Comment by michalk8** [comment] 2022-03-17 12:20
> @michalk8, it seems like we write an AnnData object to AnnData.uns, do we really want to do this? @ivirshup asked me that recently as well.

Should be doable in the newest `AnnData` version, let's stick with this. Will update the requirements + add a test case for this.

**Comment by ivirshup** [comment] 2022-03-17 12:30
I think it's fine, this should work with `anndata==0.8.0` (IIRC @cramsuig has confirmed this). I was more curious about why it was being done this way.

**Comment by Marius1311** [comment] 2022-03-17 12:59
Thanks! Anything to be done here @michalk8 to help @kmh005 ?

**Comment by michalk8** [comment] 2022-03-18 00:11
> Thanks! Anything to be done here @michalk8 to help @kmh005 ?

Updating to the newest `anndata` (0.8.0) should make it work. Can revert this and use `pandas.DataFrame` instead.

**Comment by kmh005** [comment] 2022-03-18 17:37
Thanks for you help with this. My pip install version is 0.8.0rc2.dev4+g8cc6ddc . Is this the recommended version?

**Comment by michalk8** [comment] 2022-03-21 13:16
> Thanks for you help with this. My pip install version is 0.8.0rc2.dev4+g8cc6ddc . Is this the recommended version?

I've changed it so that a `dict` is saved, instead of `AnnData`. You can try updating `CellRank` to `dev` as `pip install git+https://github.com/theislab/cellrank@dev`

Closing this via #841 , feel free to re-open if any related problems arise.

**Closed by michalk8** 2022-03-21 13:16 UTC
Labels: bug

**Comment by ivirshup** [comment] 2022-03-21 16:06
@michalk8, why did you end up removing that? Did you just not want to rely on `anndata>=0.8`?

**Comment by michalk8** [comment] 2022-03-21 16:58
> @michalk8, why did you end up removing that? Did you just not want to rely on anndata>=0.8?

Yes, since it's the newest version and we'd need it only in this place. For compatibility with `scanpy/scvelo`, think it' better not to have this stricter requirement.

**Comment by kmh005** [comment] 2022-03-21 18:33
Hi,
I set my pip install to 0.8.0 as instructed. I get a different error trying to save the anndata, any guidance most appreciated.

```
import anndata
adata.write("scvelo.cr.5.h5ad")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/utils.py:214, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    213 try:
--> 214     return func(elem, key, val, *args, **kwargs)
    215 except Exception as e:

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/specs/registry.py:175, in write_elem(f, k, elem, modifiers, *args, **kwargs)
    174 else:
--> 175     _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/specs/registry.py:64, in IORegistry.get_writer(self, dest_type, typ, modifiers)
     63 if (dest_type, typ, modifiers) not in self.write:
---> 64     raise TypeError(
     65         f"No method has been defined for writing {typ} elements to {dest_type}"
     66     )
     68 return self.write[(dest_type, typ, modifiers)]

TypeError: No method has been defined for writing <class 'cellrank.tl._lineage.Lineage'> elements to <class 'h5py._hl.group.Group'>

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Input In [18], in <cell line: 2>()
      1 import anndata
----> 2 adata.write("scvelo.cr.5.h5ad")

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_core/anndata.py:1918, in AnnData.write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1915 if filename is None:
   1916     filename = self.filename
-> 1918 _write_h5ad(
   1919     Path(filename),
   1920     self,
   1921     compression=compression,
   1922     compression_opts=compression_opts,
   1923     force_dense=force_dense,
   1924     as_dense=as_dense,
   1925 )
   1927 if self.isbacked:
   1928     self.file.filename = filename

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/h5ad.py:100, in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
     98 write_elem(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
     99 write_elem(f, "var", adata.var, dataset_kwargs=dataset_kwargs)
--> 100 write_elem(f, "obsm", dict(adata.obsm), dataset_kwargs=dataset_kwargs)
    101 write_elem(f, "varm", dict(adata.varm), dataset_kwargs=dataset_kwargs)
    102 write_elem(f, "obsp", dict(adata.obsp), dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/utils.py:214, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    211 @wraps(func)
    212 def func_wrapper(elem, key, val, *args, **kwargs):
    213     try:
--> 214         return func(elem, key, val, *args, **kwargs)
    215     except Exception as e:
    216         if "Above error raised while writing key" in format(e):

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/specs/registry.py:175, in write_elem(f, k, elem, modifiers, *args, **kwargs)
    171     _REGISTRY.get_writer(dest_type, (t, elem.dtype.kind), modifiers)(
    172         f, k, elem, *args, **kwargs
    173     )
    174 else:
--> 175     _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/specs/registry.py:24, in write_spec.<locals>.decorator.<locals>.wrapper(g, k, *args, **kwargs)
     22 @wraps(func)
     23 def wrapper(g, k, *args, **kwargs):
---> 24     result = func(g, k, *args, **kwargs)
     25     g[k].attrs.setdefault("encoding-type", spec.encoding_type)
     26     g[k].attrs.setdefault("encoding-version", spec.encoding_version)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/specs/methods.py:281, in write_mapping(f, k, v, dataset_kwargs)
    279 g = f.create_group(k)
    280 for sub_k, sub_v in v.items():
--> 281     write_elem(g, sub_k, sub_v, dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/scvelo/lib/python3.9/site-packages/anndata/_io/utils.py:220, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    218 else:
    219     parent = _get_parent(elem)
--> 220     raise type(e)(
    221         f"{e}\n\n"
    222         f"Above error raised while writing key {key!r} of {type(elem)} "
    223         f"to {parent}"
    224     ) from e

TypeError: No method has been defined for writing <class 'cellrank.tl._lineage.Lineage'> elements to <class 'h5py._hl.group.Group'>

Above error raised while writing key 'terminal_states_memberships' of <class 'h5py._hl.group.Group'> to /```

**Comment by michalk8** [comment] 2022-03-21 22:43
>  I set my pip install to 0.8.0 as instructed. I get a different error trying to save the anndata, any guidance most appreciated.

Seems like in `anndata==0.8.0` with the IOSpec changes, writing `Lineage` class is broken, minimal reproducible example:
```python
from anndata import AnnData
import cellrank as cr
import numpy as np
import scanpy as sc

lin = cr.tl.Lineage(np.random.normal(size=(10, 3)), names=["foo", "bar", "baz"])
adata = AnnData(X=np.random.normal(size=(10, 3)), obsm={"lin": lin})

sc.write("foo.h5ad", adata)
```

I will implement a proper reader/writer in #777 and request `anndata>=0.8.0` + revert the changed made in #841 .
In the meantime, I'd recommend downgrading `anndata<0.8` and installing cellrank from `master` as `pip install git+https://github.com/theislab/cellrank` as tests in #844 passed (with some unrelated exceptions).

**Comment by michalk8** [comment] 2022-03-22 17:35
Hmm, this is unexpected. As a last resort, you can remove the values that cause this issue before saving:
```python
del adata.uns['coarse_fwd']['coarse_init_dist']
try:
    del adata.uns['coarse_fwd']['coarse_stat_dist']
except KeyError:
    pass
```

**Comment by AkilaRanjith** [comment] 2022-06-07 18:08
Hello All,
I am also using Anndata=0.8.0. I am not able to save adata in h5ad format.
Here is the sample code
`import anndata
adata=anndata.read_h5ad("/home/Akila/input.h5ad")
adata.write("/home/Akila/BA9.h5ad")`

Error message:
TypeError: No method has been defined for writing <class 'numpy.matrix'> elements to <class 'h5py._hl.group.Group'>

Above error raised while writing key 'X' of <class 'h5py._hl.group.Group'> to /

Please advice

**Comment by yotamcons** [comment] 2022-06-19 15:35
I also had an issue with saving an AnnData object (AnnData==0.8.0),
due to adata.obsm containig a pandas series.

TypeError: No method has been defined for writing <class 'pandas.core.series.Series'> elements to <class 'h5py._hl.group.Group'>

I ended up changing the datatype to pandas DataFrame and the saving went through.

**Comment by Marius1311** [comment] 2022-06-21 11:34
Hi @michalk8, is there anything for us to do here?

**Comment by michalk8** [comment] 2022-06-21 12:13
Should've be fixed on master long ago.

**Comment by spkhowe** [comment] 2023-02-23 05:58
Hello, I am having a similar problem as users above. 
I downgraded to ```anndata=0.7.8``` and ```cellrank=1.5.1```
I also tried with ```pip install git+https://github.com/theislab/cellrank```
Any ideas for how to resolve this?
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/utils.py:214, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    213 try:
--> 214     return func(elem, key, val, *args, **kwargs)
    215 except Exception as e: 

 File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/specs/registry.py:175, in write_elem(f, k, elem, modifiers, *args, **kwargs)
    174 else:
--> 175     _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/specs/registry.py:64, in IORegistry.get_writer(self, dest_type, typ, modifiers)
     63 if (dest_type, typ, modifiers) not in self.write:
---> 64     raise TypeError(
     65         f"No method has been defined for writing {typ} elements to {dest_type}"
     66     )
     68 return self.write[(dest_type, typ, modifiers)]

TypeError: No method has been defined for writing <class 'cellrank.tl._lineage.Lineage'> elements to <class 'h5py._hl.group.Group'>
</code>
The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In [14], line 1
----> 1 adata.write_h5ad(f'/home/gridsan/showe/neuroTF_shared/mouse_cortex_development/scVelo/vk08.c02.lineage.drivers.h5ad')

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_core/anndata.py:1918, in AnnData.write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1915 if filename is None:
   1916     filename = self.filename
-> 1918 _write_h5ad(
   1919     Path(filename),
   1920     self,
   1921     compression=compression,
   1922     compression_opts=compression_opts,
   1923     force_dense=force_dense,
   1924     as_dense=as_dense,
   1925 )
   1927 if self.isbacked:
   1928     self.file.filename = filename

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/h5ad.py:100, in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
     98 write_elem(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
     99 write_elem(f, "var", adata.var, dataset_kwargs=dataset_kwargs)
--> 100 write_elem(f, "obsm", dict(adata.obsm), dataset_kwargs=dataset_kwargs)
    101 write_elem(f, "varm", dict(adata.varm), dataset_kwargs=dataset_kwargs)
    102 write_elem(f, "obsp", dict(adata.obsp), dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/utils.py:214, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    211 @wraps(func)
    212 def func_wrapper(elem, key, val, *args, **kwargs):
    213     try:
--> 214         return func(elem, key, val, *args, **kwargs)
    215     except Exception as e:
    216         if "Above error raised while writing key" in format(e):

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/specs/registry.py:175, in write_elem(f, k, elem, modifiers, *args, **kwargs)
    171     _REGISTRY.get_writer(dest_type, (t, elem.dtype.kind), modifiers)(
    172         f, k, elem, *args, **kwargs
    173     )
    174 else:
--> 175     _REGISTRY.get_writer(dest_type, t, modifiers)(f, k, elem, *args, **kwargs)

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/specs/registry.py:24, in write_spec.<locals>.decorator.<locals>.wrapper(g, k, *args, **kwargs)
     22 @wraps(func)
     23 def wrapper(g, k, *args, **kwargs):
---> 24     result = func(g, k, *args, **kwargs)
     25     g[k].attrs.setdefault("encoding-type", spec.encoding_type)
     26     g[k].attrs.setdefault("encoding-version", spec.encoding_version)

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/specs/methods.py:281, in write_mapping(f, k, v, dataset_kwargs)
    279 g = f.create_group(k)
    280 for sub_k, sub_v in v.items():
--> 281     write_elem(g, sub_k, sub_v, dataset_kwargs=dataset_kwargs)

File ~/.conda/envs/cellrank/lib/python3.9/site-packages/anndata/_io/utils.py:220, in report_write_key_on_error.<locals>.func_wrapper(elem, key, val, *args, **kwargs)
    218 else:
    219     parent = _get_parent(elem)
--> 220     raise type(e)(
    221         f"{e}\n\n"
    222         f"Above error raised while writing key {key!r} of {type(elem)} "
    223         f"to {parent}"
    224     ) from e

TypeError: No method has been defined for writing <class 'cellrank.tl._lineage.Lineage'> elements to <class 'h5py._hl.group.Group'>

Above error raised while writing key 'to_terminal_states' of <class 'h5py._hl.group.Group'> to / 
```

**Comment by ShobiStassen** [comment] 2023-05-03 06:38
hi @spkhowe did you manage to solve your problem? I experience the same issue but am on anndata 0.8.0 and cellrank-krylov 1.5.1

```
TypeError: No method has been defined for writing <class 'cellrank.tl._lineage.Lineage'> elements to <class 'h5py._hl.group.Group'>

Above error raised while writing key 'terminal_states_memberships' of <class 'h5py._hl.group.Group'> to /
```

**Comment by nleroy917** [comment] 2023-05-18 18:14
For me, the issue was resolved when I explicitly cast the `.X` matrix to a `csr_matrix`:

```python
from scipy.sparse import csr_matrix
adata = sc.AnnData(csr_matrix(mtx), obs=barcodes, var=peaks)
```
