### ISSUE TITLE
can not loading the cellrank datasets

### ISSUE THREAD

**Issue by IHMTDaiy** [theislab/cellrank#1238] opened 2024-12-05 02:35 UTC
...

```python
...WARNING: Failed to open the url with default certificates, trying with certifi.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/scanpy/readwrite.py:1001, in _download(url, path)
   1000 try:
-> 1001     open_url = urlopen(req)
   1002 except URLError:

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:214, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    213     opener = _opener
--> 214 return opener.open(url, data, timeout)

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:523, in OpenerDirector.open(self, fullurl, data, timeout)
    522     meth = getattr(processor, meth_name)
--> 523     response = meth(req, response)
    525 return response

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:632, in HTTPErrorProcessor.http_response(self, request, response)
    631 if not (200 <= code < 300):
--> 632     response = self.parent.error(
    633         'http', request, response, code, msg, hdrs)
    635 return response

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:561, in OpenerDirector.error(self, proto, *args)
    560 args = (dict, 'default', 'http_error_default') + orig_args
--> 561 return self._call_chain(*args)

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:494, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    493 func = getattr(handler, meth_name)
--> 494 result = func(*args)
    495 if result is not None:

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:641, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    640 def http_error_default(self, req, fp, code, msg, hdrs):
--> 641     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

HTTPError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 adata = cr.datasets.pancreas()
      2 scv.pl.proportions(adata)
      3 adata

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/cellrank/datasets.py:112, in pancreas(path, kind, **kwargs)
    109 path = f"{path}_{kind}{ext}"
    111 if kind == "raw":
--> 112     return _load_dataset_from_url(path, *_datasets["pancreas"], **kwargs)
    113 if kind == "preprocessed":
    114     return _load_dataset_from_url(path, *_datasets["pancreas_preprocessed"], **kwargs)

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/cellrank/datasets.py:67, in _load_dataset_from_url(fpath, url, expected_shape, **kwargs)
     64 kwargs.setdefault("sparse", True)
     65 kwargs.setdefault("cache", True)
---> 67 adata = read(fpath, backup_url=url, **kwargs)
     69 if adata.shape != expected_shape:
     70     raise ValueError(f"Expected `anndata.AnnData` object to have shape `{expected_shape}`, found `{adata.shape}`.")

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/legacy_api_wrap/__init__.py:82, in legacy_api.<locals>.wrapper.<locals>.fn_compatible(*args_all, **kw)
     79 @wraps(fn)
     80 def fn_compatible(*args_all: P.args, **kw: P.kwargs) -> R:
     81     if len(args_all) <= n_positional:
---> 82         return fn(*args_all, **kw)
     84     args_pos: P.args
     85     args_pos, args_rest = args_all[:n_positional], args_all[n_positional:]

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/scanpy/readwrite.py:130, in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    128 filename = Path(filename)  # allow passing strings
    129 if is_valid_filename(filename):
--> 130     return _read(
    131         filename,
    132         backed=backed,
    133         sheet=sheet,
    134         ext=ext,
    135         delimiter=delimiter,
    136         first_column_names=first_column_names,
    137         backup_url=backup_url,
    138         cache=cache,
    139         cache_compression=cache_compression,
    140         **kwargs,
    141     )
    142 # generate filename and read to dict
    143 filekey = str(filename)

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/scanpy/readwrite.py:760, in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
    758 else:
    759     ext = is_valid_filename(filename, return_ext=True)
--> 760 is_present = _check_datafile_present_and_download(filename, backup_url=backup_url)
    761 if not is_present:
    762     logg.debug(f"... did not find original file {filename}")

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/scanpy/readwrite.py:1054, in _check_datafile_present_and_download(path, backup_url)
   1051     logg.info(f"creating directory {path.parent}/ for saving data")
   1052     path.parent.mkdir(parents=True)
-> 1054 _download(backup_url, path)
   1055 return True

File ~/miniconda3/envs/sc2024/lib/python3.9/site-packages/scanpy/readwrite.py:1011, in _download(url, path)
   1007     from ssl import create_default_context
   1009     from certifi import where
-> 1011     open_url = urlopen(req, context=create_default_context(cafile=where()))
   1013 with open_url as resp:
   1014     total = resp.info().get("content-length", None)

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:214, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    212 else:
    213     opener = _opener
--> 214 return opener.open(url, data, timeout)

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:523, in OpenerDirector.open(self, fullurl, data, timeout)
    521 for processor in self.process_response.get(protocol, []):
    522     meth = getattr(processor, meth_name)
--> 523     response = meth(req, response)
    525 return response

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:632, in HTTPErrorProcessor.http_response(self, request, response)
    629 # According to RFC 2616, "2xx" code indicates that the client's
    630 # request was successfully received, understood, and accepted.
    631 if not (200 <= code < 300):
--> 632     response = self.parent.error(
    633         'http', request, response, code, msg, hdrs)
    635 return response

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:561, in OpenerDirector.error(self, proto, *args)
    559 if http_err:
    560     args = (dict, 'default', 'http_error_default') + orig_args
--> 561     return self._call_chain(*args)

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:494, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    492 for handler in handlers:
    493     func = getattr(handler, meth_name)
--> 494     result = func(*args)
    495     if result is not None:
    496         return result

File ~/miniconda3/envs/sc2024/lib/python3.9/urllib/request.py:641, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    640 def http_error_default(self, req, fp, code, msg, hdrs):
--> 641     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 403: Forbidden
```

```pytb
...
```

#### Versions:

> ...

**Comment by WeilerP** [comment] 2024-12-05 10:11
Just checked and everything works for me, so it seems to be an issue on your end @IHMTDaiy. Also closing the issue since it is not reproducible as the requested details are not given.

**Closed by WeilerP** 2024-12-05 10:11 UTC
Labels: bug
