### ISSUE TITLE
PAGA with Pie Charts

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#25] opened 2020-03-20 11:44 UTC
Leander and Volker both had similar bugs where their PAGA with pie charts looks something like this: 
![image](https://user-images.githubusercontent.com/24494650/77160832-82385000-6aa8-11ea-8aee-8dc2804b2798.png)

Any idea what may be happening here?

**Comment by michalk8** [comment] 2020-03-20 11:50
I suspect it might be because how pie charts are implemente in paga, see below:
https://github.com/theislab/scanpy/blob/master/scanpy/plotting/_tools/paga.py#L825

**Comment by Marius1311** [comment] 2020-03-20 13:40
Is there any easy fix for this?

**Comment by michalk8** [comment] 2020-03-20 14:12
One option would be using this: https://matplotlib.org/3.1.0/gallery/lines_bars_and_markers/scatter_piecharts.html
Instead of relying on `ax.pie` and the trickery there, we could use many scatterplots and create the piecharts ourselves. This seems like an easy fix (implementation-wise), though i'm not sure if the problem will disappear. I will start working on it, once I'm done, I'll notify Volker and Leander to try it out, since I don't have the data to test it.

**Comment by michalk8** [comment] 2020-03-20 14:20
The harder option would be to debug the code, of course.

**Comment by michalk8** [comment] 2020-03-20 15:18
@VolkerBergen @le-ander 
Could anyone of you please try whether the fix I have under my fork of scanpy (here: https://github.com/michalk8/scanpy) works for and produces the correct plot?
If it works, I will make a PR. Thanks in advance!

**Comment by VolkerBergen** [comment] 2020-03-20 15:27
Yes, works for me!

**Comment by VolkerBergen** [comment] 2020-03-20 15:27
![image](https://user-images.githubusercontent.com/31883718/77178696-bb33ed00-6ac7-11ea-9a94-83c7a52bfa7c.png)

**Comment by michalk8** [comment] 2020-03-20 15:54
> Yes, works for me!

Great, thanks!

**Comment by Marius1311** [comment] 2020-03-23 08:56
Thanks guys! @le-ander , does this fix the problem for you as well?

**Comment by le-ander** [comment] 2020-03-23 10:57
yep, seems to be fixed in the pull request. great! :)

**Comment by Marius1311** [comment] 2020-03-23 14:18
Nice, thanks for checking it out!!

**Comment by Marius1311** [comment] 2020-03-25 11:10
Hi Mike! I'm experimenting with the new `cr.pl.cluster_fates(..., mode='paga_pie', ...)`. See below for my observations.

# Default settings
`cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", )` 
![image](https://user-images.githubusercontent.com/24494650/77529740-7c6bb180-6e90-11ea-9c20-81654f664ce9.png)
Works as expected, nice!

# No Basis specified
`cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis=None, )`
![image](https://user-images.githubusercontent.com/24494650/77529772-90afae80-6e90-11ea-8786-16137b42c091.png)
No more pie charts here...

# Legend location
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", legend_loc='right_margin')
![image](https://user-images.githubusercontent.com/24494650/77529843-b046d700-6e90-11ea-9e13-757aeedad878.png)
Where did the legend go? Do we use different keywords for the legend than scanpy and scvelo? That would be a bit confusing

# Including PAGA kwargs
```python
paga_kwargs={'fontsize': 15, 'fontweight': 10,  'node_size_scale': 2, 'frameon': False, 'edge_width_scale': 2}
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", **paga_kwargs)
```
raises

```python
--------------------
AttributeErrorTraceback (most recent call last)
<ipython-input-31-308f7e2cd47c> in <module>
      2 
      3 paga_kwargs={'fontsize': 15, 'fontweight': 10,  'node_size_scale': 2, 'frameon': False, 'edge_width_scale': 2, 'threshhold': 0}
----> 4 cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", **paga_kwargs)

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in cluster_fates(adata, cluster_key, clusters, lineages, mode, final, basis, show_cbar, ncols, sharey, save, legend_kwargs, figsize, dpi, **kwargs)
    371         if "paga" not in adata.uns:
    372             raise KeyError("Compute PAGA first as `scanpy.tl.paga()`.")
--> 373         fig = plot_paga_pie()
    374     elif mode == "violin":
    375         fig = plot_violin_no_cluster_key() if cluster_key is None else plot_violin()

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in plot_paga_pie()
    207             kwargs["node_colors"] = kwargs.pop("colors")
    208 
--> 209         scv.pl.paga(adata, **kwargs)
    210         dummy_pos = adata.uns["paga"]["pos"][0]
    211 

~/Projects/scvelo/scvelo/plotting/paga.py in paga(adata, basis, vkey, color, layer, title, threshold, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, random_state, pos, node_colors, normalize_to_color, cmap, cax, cb_kwds, add_pos, export_to_gexf, plot, use_raw, size, groups, components, figsize, dpi, show, save, ax, ncols, scatter_flag, **kwargs)
    118             if 'alpha' not in kwargs: kwargs['alpha'] = .5
    119             ax = scatter(adata, basis=basis, x=x, y=y, vkey=vkey, layer=layer, color=color, size=size, title=title,
--> 120                          ax=ax, save=None, zorder=0, show=False, **kwargs)
    121         scanpy_paga(adata, ax=ax, show=False,  **paga_kwargs,
    122                     text_kwds={'zorder': 1000, 'alpha': legend_loc == 'on data'})

~/Projects/scvelo/scvelo/plotting/scatter.py in scatter(adata, x, y, basis, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_fontsize, legend_fontweight, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, show_density, show_assignments, show_linear_fit, show_polyfit, rug, add_text, add_text_pos, add_outline, outline_width, outline_color, n_convolve, smooth, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    352                         logg.warn('Invalid color key. Using grey instead.')
    353 
--> 354             smp = ax.scatter(x, y, c=c, alpha=alpha, marker='.', zorder=zorder, **kwargs)
    355 
    356             if add_outline:

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, plotnonfinite, **kwargs)
   4430                 )
   4431         collection.set_transform(mtransforms.IdentityTransform())
-> 4432         collection.update(kwargs)
   4433 
   4434         if colors is None:

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in update(self, props)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in <listcomp>(.0)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in _update_property(self, k, v)
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 

AttributeError: 'PathCollection' object has no property 'fontweight'

> /Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py(1002)_update_property()
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 
```

Let's not use the `fontweight`:
```python
paga_kwargs={'fontsize': 15,  'node_size_scale': 2, 'frameon': False, 'edge_width_scale': 2}
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", **paga_kwargs)
```
gives
![image](https://user-images.githubusercontent.com/24494650/77530225-4aa71a80-6e91-11ea-903a-2c28e0c74a56.png)

Nice, that works again.

# Changing the threshold
Above, there was no connection between `Ngn3 high EP` and `Pre-endocrine`. I would like to add one by lowering the threshold for removing edges:
```pyton
paga_kwargs={'fontsize': 15,  'node_size_scale': 2, 'frameon': False, 'edge_width_scale': 2, 'threshhold': 0.02}
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", **paga_kwargs)
```
raises
```python
--------------------
AttributeErrorTraceback (most recent call last)
<ipython-input-19-a445d584545b> in <module>
      2 
      3 paga_kwargs={'fontsize': 15,  'node_size_scale': 2, 'frameon': False, 'edge_width_scale': 2, 'threshhold': 0.02}
----> 4 cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", **paga_kwargs)

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in cluster_fates(adata, cluster_key, clusters, lineages, mode, final, basis, show_cbar, ncols, sharey, save, legend_kwargs, figsize, dpi, **kwargs)
    371         if "paga" not in adata.uns:
    372             raise KeyError("Compute PAGA first as `scanpy.tl.paga()`.")
--> 373         fig = plot_paga_pie()
    374     elif mode == "violin":
    375         fig = plot_violin_no_cluster_key() if cluster_key is None else plot_violin()

~/Projects/cellrank/cellrank/plotting/_cluster_fates.py in plot_paga_pie()
    207             kwargs["node_colors"] = kwargs.pop("colors")
    208 
--> 209         scv.pl.paga(adata, **kwargs)
    210         dummy_pos = adata.uns["paga"]["pos"][0]
    211 

~/Projects/scvelo/scvelo/plotting/paga.py in paga(adata, basis, vkey, color, layer, title, threshold, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, random_state, pos, node_colors, normalize_to_color, cmap, cax, cb_kwds, add_pos, export_to_gexf, plot, use_raw, size, groups, components, figsize, dpi, show, save, ax, ncols, scatter_flag, **kwargs)
    118             if 'alpha' not in kwargs: kwargs['alpha'] = .5
    119             ax = scatter(adata, basis=basis, x=x, y=y, vkey=vkey, layer=layer, color=color, size=size, title=title,
--> 120                          ax=ax, save=None, zorder=0, show=False, **kwargs)
    121         scanpy_paga(adata, ax=ax, show=False,  **paga_kwargs,
    122                     text_kwds={'zorder': 1000, 'alpha': legend_loc == 'on data'})

~/Projects/scvelo/scvelo/plotting/scatter.py in scatter(adata, x, y, basis, vkey, color, use_raw, layer, color_map, colorbar, palette, size, alpha, linewidth, linecolor, perc, groups, sort_order, components, projection, legend_loc, legend_fontsize, legend_fontweight, xlabel, ylabel, title, fontsize, figsize, xlim, ylim, show_density, show_assignments, show_linear_fit, show_polyfit, rug, add_text, add_text_pos, add_outline, outline_width, outline_color, n_convolve, smooth, rescale_color, color_gradients, dpi, frameon, zorder, ncols, nrows, wspace, hspace, show, save, ax, **kwargs)
    352                         logg.warn('Invalid color key. Using grey instead.')
    353 
--> 354             smp = ax.scatter(x, y, c=c, alpha=alpha, marker='.', zorder=zorder, **kwargs)
    355 
    356             if add_outline:

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, plotnonfinite, **kwargs)
   4430                 )
   4431         collection.set_transform(mtransforms.IdentityTransform())
-> 4432         collection.update(kwargs)
   4433 
   4434         if colors is None:

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in update(self, props)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in <listcomp>(.0)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py in _update_property(self, k, v)
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 

AttributeError: 'PathCollection' object has no property 'threshhold'

> /Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/matplotlib/artist.py(1002)_update_property()
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 
```

These are my observations so far.

**Comment by Marius1311** [comment] 2020-03-25 11:12
Oh, lastly, we seem so far to ignore the argument `frameon=False`, which says that there should be no frame drawn around the plot...

**Comment by VolkerBergen** [comment] 2020-03-25 11:30
It's 'right margin' or simply 'right' instead of 'right_margin' 
One could further use https://github.com/Phlya/adjustText to adjust the cluster annotations to not overlap with the paga nodes, but to be placed next to it.

**Comment by michalk8** [comment] 2020-03-25 11:46
1. No basis specified works correctly now.
2. Legend location - there are now 2 legends, you control the one from scvelo using `legend_loc`,
the other one using `legend_kwargs`.
3., 4. @VolkerBergen I made a PR for fontweight and frameon for paga here: https://github.com/theislab/scvelo/pull/174
5. Threshold: you have a typo there - `threshhold`.

**Comment by michalk8** [comment] 2020-03-25 11:59
To clarify, you can use `legend_loc` to position scVelo's legend and `legend_kwargs` to position the 2nd legend (for pie chart) + `legend_kwargs` stylizes both legends (e.g. `ncol=2`).

**Comment by Marius1311** [comment] 2020-03-25 18:25
> It's 'right margin' or simply 'right' instead of 'right_margin'
> One could further use https://github.com/Phlya/adjustText to adjust the cluster annotations to not overlap with the paga nodes, but to be placed next to it.

sorry, my bad...

**Comment by Marius1311** [comment] 2020-03-25 18:27
> 1. No basis specified works correctly now.
> 2. Legend location - there are now 2 legends, you control the one from scvelo using `legend_loc`,
>    the other one using `legend_kwargs`.
>    3., 4. @VolkerBergen I made a PR for fontweight and frameon for paga here: [theislab/scvelo#174](https://github.com/theislab/scvelo/pull/174)
> 3. Threshold: you have a typo there - `threshhold`.

Man, I made a lot of stupid mistakes there! Thanks for pointing it out and fixing the rest.

**Comment by Marius1311** [comment] 2020-03-26 14:05
Works much better for me now, but I'm not quite happy with the edge with yet. With default PAGA (scanpy), I get for `edge_width_scale=1` (default):

![image](https://user-images.githubusercontent.com/24494650/77655146-53bbe880-6f72-11ea-9dc7-4373c4878924.png)

If I increase it to say 5, I get
![image](https://user-images.githubusercontent.com/24494650/77655199-6504f500-6f72-11ea-8fb1-a19ff7af0f1b.png)
So works as expected. Now, with cellrank and pie charts, I get for `edge_width_scale=1`:
![image](https://user-images.githubusercontent.com/24494650/77655324-89f96800-6f72-11ea-89a5-3adca81a2a42.png)

Now I increase it to 5:
![image](https://user-images.githubusercontent.com/24494650/77655355-95e52a00-6f72-11ea-892c-b465a052e8c7.png)

No changes. Let's put it to 1e5:
![image](https://user-images.githubusercontent.com/24494650/77655404-a5fd0980-6f72-11ea-91a4-6d77802e466e.png)

Still no changes. However, I can see changes when I go lower, say to 0.1:
![image](https://user-images.githubusercontent.com/24494650/77655444-b4e3bc00-6f72-11ea-8c08-270ae424ebf0.png)

So only one direction works, for whatever reason.

**Comment by michalk8** [comment] 2020-03-26 15:06
That's because `max_edge_width=1` in scVelo's paga. Set it higher and you'll see results.
In `sc.pl.paga`, it's None.

**Comment by Marius1311** [comment] 2020-03-27 09:13
I see, thanks!

**Comment by Marius1311** [comment] 2020-03-27 09:24
Is is somehow possible to actually position the scvelo legend outside the plot, like in `scv.pl.scatter`? When I call 
```
paga_kwargs={'fontsize': 15,  'node_size_scale': 2, 'frameon': False, 
             'dpi': 200, 'threshold': 0.1, 'max_edge_width': 4, 'edge_width_scale': 1.5}
cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis="umap", 
                    title='CellRank Fate Probabilities', legend_loc='right margin', **paga_kwargs)
```
I get
![image](https://user-images.githubusercontent.com/24494650/77741313-fb89f280-7014-11ea-8de5-2dda19a59274.png)

so the scvelo legend isn't actually at the right margin. I was hoping to get something more like this
![image](https://user-images.githubusercontent.com/24494650/77741353-10668600-7015-11ea-998a-e11810ee03a8.png)

where the legend is really outside the plot. @VolkerBergen , maybe you can help?

**Comment by michalk8** [comment] 2020-03-27 10:06
Now it does.

**Comment by VolkerBergen** [comment] 2020-03-27 10:52
has sth. to do with how scvelo 'paga' is called.

With scvelo directly the legend_loc works fine
`scv.pl.paga(adata, basis='umap', threshold=.05, frameon=False, legend_loc='right')`
![image](https://user-images.githubusercontent.com/31883718/77748911-6b05df00-7021-11ea-8803-05373b1296f3.png)

**Comment by Marius1311** [comment] 2020-03-27 17:22
thanks! Legend positioning works now, but I still get weird stuff if I don't specify a basis:
`cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis='umap')`
gives
![image](https://user-images.githubusercontent.com/24494650/77782410-8be92700-7057-11ea-8537-a47c4e5a3a99.png)
while
`cr.pl.cluster_fates(adata, cluster_key='clusters', mode='paga_pie', basis=None)`
gives
![image](https://user-images.githubusercontent.com/24494650/77782441-99061600-7057-11ea-84f1-cbbbf020bf4a.png)

@michalk8 , is this fixed by https://github.com/theislab/scanpy/pull/1123? What's the state of the art there?

**Comment by Marius1311** [comment] 2020-03-27 17:27
Could we also add a name to each of the legend? 
![image](https://user-images.githubusercontent.com/24494650/77783088-8a6c2e80-7058-11ea-9a43-6bd76b84616f.png)

So that it's clear that one legend is for the clusters, while the other is for final cells/root cells?

**Comment by michalk8** [comment] 2020-03-27 17:39
I've added the label for legend. As for the bug, it's not yet merged, I am in the process of creating a test + 1 more benchmark to see if there's an improvement.

**Comment by Marius1311** [comment] 2020-03-31 09:41
Thanks Mike! Keep me updated with regards to your scanpy PR please.

**Comment by Marius1311** [comment] 2020-04-07 08:16
Any update on the scanpy PR?

**Comment by michalk8** [comment] 2020-04-07 11:21
Isaac doesn't like that it's much slower than the original, so I may have to debug the original code to see where the underlying issue is.

**Comment by Marius1311** [comment] 2020-04-08 09:00
That doesn't sound like a lot of fun... Yet, it would be important to make sure our plots are reproducible...

**Comment by Marius1311** [comment] 2020-04-08 12:47
Two minor bugs
- when saving the figure as a pdf, the cluster legend is on the data, no matter what I specified. In fact, I get it twice, see below
- when saving as png, the resolution is really low, even though I specified `dpi=300` and in my jupyter notebook, the resolution looks super high. 

[14.5_paga_pie.pdf](https://github.com/theislab/cellrank/files/4450523/14.5_paga_pie.pdf)

**Comment by VolkerBergen** [comment] 2020-04-30 07:24
Fully re-implemented `tl.paga` and `pl.paga` to properly handle directed trees. Please have a look whether that also solves your issue.
```
scv.pl.paga(adata, color=cluster_key, transitions=None, node_colors='to_final_cells', basis='umap')
```
now returns 
![image](https://user-images.githubusercontent.com/31883718/80683323-53a88e80-8ac4-11ea-9304-b0765af7891c.png)

You may need to adjust the `cluster_fates` implementation slightly.

**Comment by michalk8** [comment] 2020-04-30 15:00
@VolkerBergen thanks, looks great, will test it out later today.

**Comment by michalk8** [comment] 2020-04-30 22:31
Ok, I've tested it and I have 1 request and 1 issue to report:
Request (when using `sc.tl.paga` instead of `scv.tl.paga`), I get:
```python
KeyError                                  Traceback (most recent call last)
<ipython-input-65-c3a41d5a1e0e> in <module>
----> 1 scv.pl.paga(adata, color='clusters', node_colors=pos, transitions=None)

~/projects/scvelo/scvelo/plotting/paga.py in paga(adata, basis, vkey, color, layer, title, threshold, layout, layout_kwds, init_pos, root, labels, single_component, dashed_edges, solid_edges, transitions, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, random_state, pos, node_colors, normalize_to_color, cmap, cax, cb_kwds, add_pos, export_to_gexf, plot, use_raw, size, groups, components, figsize, dpi, show, save, ax, ncols, scatter_flag, **kwargs)
    256 
    257         _paga(adata, ax=ax, show=False,  **paga_kwargs,
--> 258                     text_kwds={'zorder': 1000, 'alpha': legend_loc == 'on data'})
    259 
    260         savefig_or_show(dpi=dpi, save=save, show=show)

~/projects/scvelo/scvelo/plotting/paga.py in _paga(adata, threshold, color, layout, layout_kwds, init_pos, root, labels, single_component, solid_edges, dashed_edges, transitions, fontsize, fontweight, fontoutline, text_kwds, node_size_scale, node_size_power, edge_width_scale, min_edge_width, max_edge_width, arrowsize, title, random_state, pos, normalize_to_color, cmap, cax, colorbar, cb_kwds, frameon, add_pos, export_to_gexf, use_raw, colors, groups, plot, show, save, ax)
    302 
    303     # define the adjacency matrices
--> 304     adjacency_solid = adata.uns['paga'][solid_edges].copy()
    305     adjacency_dashed = None
    306     if threshold is None:

KeyError: 'transitions_confidence'
```
I'd raise a nicer error saying that user should run `scv.tl.paga`.

Issue: running this, no output is being produced:
```python
import matplotlib.cm as cm
import matplotlib.colors as mcolors

# doesn't display anything even when changing 256 -> e.g. 3
# sc.pl.paga still produced the buggy lplot
pos = {i:{mcolors.to_hex(cm.viridis(c)): 0.003 for c in range(256)}
       for i in range(adata.uns['paga']['pos'].shape[0])}
scv.pl.paga(adata, color='clusters', node_colors=pos, transitions=None)
scv.pl.paga(adata, color='clusters', node_colors='to_final_cells', transitions=None)
```

**Comment by Marius1311** [comment] 2020-05-06 11:07
@michalk8, Volker has added a couple of nice features to his PAGA implementation, among them better support for velocities, i.e. directing the edges. Would be nice to be able to take advantage of this in `cr.pl.cluster_fates`. We can talk about in tonight in more detail. Does the above error still persist?

We will have to rename a couple of our attributes for harmonization with scvelo, but I will open a separete issue for this.

**Comment by michalk8** [comment] 2020-05-10 18:52
@VolkerBergen Another small issue: the plot is not reproducible. Running the same code twice
can sometimes produce different results.

**Comment by Marius1311** [comment] 2020-05-11 07:28
@michalk8 , can you give a MWE for Volker to reproduce this?

**Comment by VolkerBergen** [comment] 2020-05-11 09:57
Thanks, now it is. 
https://github.com/theislab/scvelo/commit/c441c725c1439570c72607eef791a9aa345e376f

**Comment by michalk8** [comment] 2020-05-11 19:40
Great, one last small issue: `title=...` is not working, i.e.
```python
scv.pl.paga(adata, title='foo')
```
still gives me `'clusters'` in the title.

**Closed** 2020-05-11 20:00 UTC
Labels: bug
