### ISSUE TITLE
Pipeline from Seurat object to CellRank

### ISSUE THREAD

**Issue by mainharryHR** [theislab/cellrank#1204] opened 2024-07-02 16:35 UTC
...
Dear Team,

I am curious if there is a pipeline starting from Seurat object to CellRank to do the trajectory or velocity ?

I am working with 30 patient samples. it seems I need to start from the files before alignments one by one in order to get the unspliced RNA. The files are super big as well. Is there any way to get around that?

Any comments are welcome.

Best

**Comment by Marius1311** [comment] 2024-07-03 10:59
Hi @mainharryHR, if you want to estimate spliced and unspliced counts, please check our velocyto, kalisto, or related tools! Other questions related the RNA velocity estimation are probably best posted in the scVelo repo.

**Comment by WeilerP** [comment] 2024-07-03 11:08
Thanks, @Marius1311. Closing the issue since it not related to CellRank directly.

**Closed by WeilerP** 2024-07-03 11:08 UTC
Labels: enhancement

**Comment by mainharryHR** [comment] 2024-07-03 13:32
> Hi @mainharryHR, if you want to estimate spliced and unspliced counts, please check our velocyto, kalisto, or related tools! Other questions related the RNA velocity estimation are probably best posted in the scVelo repo.

Thank you very much for your suggestions. My new this field, Sorry for the dumb questions. I am working on Seurat object. I am wondering where to get the unspliced RNA information.  I feel I need to use the CytoTrace for Seurat object. Any comments are welcome. 

Thank you all.

**Comment by WeilerP** [comment] 2024-07-05 08:04
You do not need unspliced counts for CytoTRACE. See [here](https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/kernels/400_cytotrace.html) or [here](https://theislab.github.io/cellrank2_reproducibility/cytotrace_kernel/embryoid_body/cytotrace.html) for an example workflow.
