### ISSUE TITLE
How to extract colors from terminal state plot?

### ISSUE THREAD

**Issue by GabrielBaldissera** [theislab/cellrank#1006] opened 2023-03-23 17:26 UTC
Hello,

I have identified the terminal states with the code below and generated the following image.

`cr.tl.terminal_states(anndata, cluster_key="Clusters", weight_connectivities=0.2)`
`cr.pl.terminal_states(anndata,dpi=400)`
`cr.pl.terminal_states(anndata,dpi=400, node_size_scale=5, size=80, edge_width_scale=1, max_edge_width=4)`
![image](https://user-images.githubusercontent.com/47226253/227284546-ad0d6f32-04de-4e2d-827c-c19ef915fe6e.png)

I want to replot it using another tool such as Seurat to keep the same aspect ratio and appearance as other plots for my publication. Do you have any suggestions on how I could do that? I tried extracting the terminal state probabilities and using them to color on Seurat but then I lost the terminal state group information in the plot.

Thanks in advance for your time!
Best regards,
Gabriel

**Comment by Marius1311** [comment] 2023-03-24 08:48
Hi @GabrielBaldissera, I guess it's easier if you work directly with the estimator object (i.e. the GPCCA estimator), that way you can directly access the terminal states memberships and colors, e.g. using https://cellrank.readthedocs.io/en/latest/api/_autosummary/estimators/cellrank.estimators.GPCCA.html#cellrank.estimators.GPCCA.terminal_states_memberships

We're currently overhauling our API, so things are in the process of changing.

**Comment by Marius1311** [comment] 2023-04-11 11:42
Hi @GabrielBaldissera, I'm closing this as I assume the issue is solved. Please re-open if that is not the case.

**Closed by Marius1311** 2023-04-11 11:42 UTC
Labels: question
