### ISSUE TITLE
Link to cellrank.org

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#169] opened 2020-06-04 15:01 UTC
Once that's done, we can use a fix by @VolkerBergen to make sure that even when the user clicks on a tutorial, the visible url remains `cellrank.readthedocs/xxx`. @VolkerBergen , can you point me to the part of the code where you do this?

**Comment by michalk8** [comment] 2020-06-07 18:04
@Marius1311 I think you need to set this up, since you're the owner, see here: https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support

**Comment by VolkerBergen** [comment] 2020-06-07 19:50
You can retrieve the notebooks from the notebook-repo (see [here](https://github.com/theislab/scvelo/blob/3708b0ce615036d5947b991e714273bd8655d06d/docs/source/conf.py#L31)), which downloads the notebooks behind the scenes and converts them to html via nbsphinx. This way, you would have your tutorials-docs also being hosted directly at cellrank.readthedocs.org.

**Comment by Marius1311** [comment] 2020-06-16 18:00
Linking to cellrank.org is done. @michalk8, we can set up the notebook download in our call on Wednesday together.

**Comment by michalk8** [comment] 2020-06-17 17:00
Thanks @VolkerBergen for the suggestion, it's done. @Marius1311 the figures look a bit off, do you know how to fix it? Afterwards, we can close this.

**Comment by michalk8** [comment] 2020-06-17 17:07
Also @VolkerBergen , upgrading to `sphinx-3.1.1` leads to the following problem (no links are present for some functions, such as `tl.partition`):
![missing_links](https://user-images.githubusercontent.com/46717574/84927758-91da2b80-b0cd-11ea-8243-98731a5aea43.png)
I think this is because of all the warnings we're getting (not included in toc tree) when building the docs (I'd like to fix them, but have no idea how + I want to be a bit stricter and have warnings as error). Do you know what might be the cause?
`

**Comment by VolkerBergen** [comment] 2020-06-17 17:35
@michalk8 I get the following error when trying to generate the html
```
Extension error:
Handler <function process_docstring at 0x12b6bbc20> for event 'autodoc-process-docstring' threw an exception
make: *** [html] Error 2
```
Maybe related?

**Comment by michalk8** [comment] 2020-06-17 17:43
Yes and no, but it has led me to this (didn't see this because of all the other warnings...).
Furthermore, I don't get that error, but digging deeper, this is the warning which causes the issue:
```
WARNING: don't know which module to import for autodocumenting 'pl.cluster_fates' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
```
Here's the related issue for sphinx version `3.1.1`: https://github.com/sphinx-doc/sphinx/issues/7844

**Comment by matthewfeickert** [comment] 2020-06-18 03:37
:wave: @michalk8, I was checking on the Sphinx Issue that I opened today and noticed that you had linked to it here. Could you please mention on the Issue that you're also running into this? The more people that are reporting the sooner it will probably get attention from the Sphinx devs.

FWIW, `pyhf` is considering temporarily pinning to have Sphinx be `sphinx<3.1.0`, so might be worth looking into for `cellrank` as well(?).

**Comment by Marius1311** [comment] 2020-06-18 09:56
@michalk8, we had that figure issue before, you remember? Last time you fixed it somehow, I can't remember how you did it though. This was a couple of months ago.

**Comment by Marius1311** [comment] 2020-06-18 09:58
By the way, @michalk8, very nice clean up of the notebooks repo! I love it!

**Comment by michalk8** [comment] 2020-06-27 13:31
This has been done, closing this. I will create a separate issue for removal of the warnings.

**Closed by michalk8** 2020-06-27 13:31 UTC
Labels: enhancement

**Comment by VolkerBergen** [comment] 2020-06-27 13:56
Sorry, forgot to reply. I know the issue and can help you with getting the right fig sizes in the converted tutorials. It's a little longer explanation. Let's disc next week.
