### ISSUE TITLE
`PseudotimeKernel` depends on deprecated function from `networkx`

### ISSUE THREAD

**Issue by jr-leary7** [theislab/cellrank#1024] opened 2023-04-21 21:53 UTC
When attempting to use `PseudotimeKernel`, the following code is called & results in an AttributeError:

```python
import networkx as nx
G = nx.from_scipy_sparse_matrix(c) if issparse(c) else nx.from_numpy_array(c)
```

The `from_scipy_sparse_matrix()` function [has been deprecated](https://github.com/python-graphblas/python-graphblas/issues/181) in favor of [`from_scipy_sparse_array()`](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_scipy_sparse_array.html#networkx.convert_matrix.from_scipy_sparse_array) as of the v3.0 release of `networkx`. The new function is a drop-in replacement (as far as I can tell) with the same arguments, so I imagine it'd be quick to just replace the import statement. 

```python
import cellrank as cr
adata = cr.datasets.pancreas_preprocessed("../example.h5ad")
pk = cr.tl.kernels.PseudotimeKernel(adata, backward=True).compute_transition_matrix()
```

```pytb
AttributeError: module 'networkx' has no attribute 'from_scipy_sparse_matrix'
```

#### Versions:

> cellrank==1.5.1 scanpy==1.9.3 anndata==0.9.1 numpy==1.23.5 numba==0.56.4 scipy==1.10.1 pandas==1.5.3 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.13.5 python-igraph==0.10.4 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by michalk8** [comment] 2023-05-01 12:23
This should be fixed on master, see [here](https://github.com/theislab/cellrank/blob/e54987b800a2a85f94c735ef0e9a33a4736f2e00/cellrank/_utils/_utils.py#L761-L765). We will be making a new release hopefully soon, in the meantime please install as `pip install git+https://github.com/theislab/cellrank`

**Closed by michalk8** 2023-05-01 12:23 UTC
Labels: bug

**Comment by hyjforesight** [comment] 2024-09-30 16:45
Hello @michalk8
I'm now using cellrank v1.5.1 and met the same error. I run 'pip install git+https://github.com/theislab/cellrank' but failed. Is it because it's trying to git clonie cellrank v2.0, which is not compatible to my v1.5.1? How can I update v1.5.1?
Thank you!
Best,
YJ

**Comment by WeilerP** [comment] 2024-09-30 16:51
@hyjforesight, any reason you want the latest version? You can install CellRank via pip or mamba/conda the standard way to get the latest released version; @michalk8's previous command was only needed before the corresponding release. If you still run into issues, I suggest creating a new environment to install the package in.

**Comment by hyjforesight** [comment] 2024-09-30 17:13
Hello @WeilerP, thank you for the response.
I installed v1.5.1 in 2022 and, as I remember, I updated several times via pip git clone from github. These updates were not released as formal versions.
Now, I'm back in China and I'm trying to reproduce my previous figures with my local computer. I just created a new environment with python 3.8 and 'pip install cellrank==1.5.1'. I guess I cannot install those updates and so now I keep meeting the `AttributeError: module 'networkx' has no attribute 'from_scipy_sparse_matrix`.
Could you please help me with this?
Thank you!

**Comment by WeilerP** [comment] 2024-10-01 06:07
You'll have to install a compatible networkx version. I strongly suggest you update to the latest version of CellRank and use a Python version that's supported for longer.
