### ISSUE TITLE
AttributeError with cr.pl.gene.trends

### ISSUE THREAD

**Issue by MarieCoutelier** [theislab/cellrank#1106] opened 2023-07-31 14:48 UTC
Hi,

I'm trying out Cellrank2 tutorial, with the suggested material. I managed to have it running up until the expression trends block, but I'm now stuck with my GAMR model and an AttributeError upon running cr.pl.gene_trends.
I followed the exact code suggested in https://cellrank.readthedocs.io/en/latest/notebooks/tutorials/general/100_getting_started.html

To generate the model, I struggled a bit and eventually had to install r-base with conda then rpy2==3.2.0 with pip. 
I have a similar issue with cr.pl.heatmap, I assume that the model itself actually has an issue.

Thanks for your help!

```
# Generating the model does not generate an error:
>>> model = cr.models.GAMR(adata)
>>> 

# The model is as follows: - is it correct? 
>>> model
<GAMR[gene=None, lineage=None, model=None]>

# Then the plotting does not work
>>> # Visualize expression trends
>>> model = cr.models.GAMR(adata)
>>> cr.pl.gene_trends(
...     adata,
...     model=model,
...     data_key="MAGIC_imputed_data",
...     genes=["GATA1", "CD34", "IRF8", "MPO"],
...     same_plot=True,
...     ncols=2,
...     time_key="palantir_pseudotime",
...     hide_cells=True
... )

```

```pytb
Computing trends using `1` core(s)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 23.39gene/s]
    Finish (0:00:00)
Traceback (most recent call last):
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/models/_base_model.py", line 63, in wrapper
    return wrapped(*args, **kwargs)
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/models/_gamr_model.py", line 199, in fit
    self._model = self._lib.gam(
AttributeError: 'NoneType' object has no attribute 'gam'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/_utils/_utils.py", line 1586, in _genesymbols
    return wrapped(*args, **kwargs)
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/pl/_gene_trend.py", line 206, in gene_trends
    all_models, models, genes, lineages = _fit_bulk(
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/pl/_utils.py", line 331, in _fit_bulk
    return _filter_models(models, return_models=return_models, filter_all_failed=filter_all_failed)
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/pl/_utils.py", line 366, in _filter_models
    model.reraise()
  File "/network/lustre/iss02/stevanin-durr/spatax/miniconda3/envs/cellrank2/lib/python3.8/site-packages/cellrank/models/_base_model.py", line 1232, in reraise
    raise type(self._exc)(f"Fatal model failure `{self}`.") from self._exc
AttributeError: Fatal model failure `<FailedModel[origin=GAMR[gene='GATA1', lineage='DCs_1', model=None]]>`.
```

#### Versions:

> cellrank==2.0.0 scanpy==1.9.3 anndata==0.9.2 numpy==1.24.4 numba==0.57.1 scipy==1.10.1 pandas==2.0.3 pygpcca==1.0.4 scikit-learn==1.1.3 statsmodels==0.14.0 scvelo==0.3.0 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by michalk8** [comment] 2023-08-16 13:50
I think the problem is because `mgcv` is not installed in that environment; [here](https://github.com/theislab/cellrank/blob/main/src/cellrank/models/_gamr_model.py#L340-L366) is code used for loading it using `rpy2` and [here](https://github.com/theislab/cellrank/blob/main/src/cellrank/models/_gamr_model.py#L90-L92) it's being called. Would check whether `model._lib` is `None` or not (will change to raise an error by default in the future if `mgcv` is not present).

**Comment by Marius1311** [comment] 2023-09-13 12:26
I suppose @michalk8's comment from above solved the issue; closing.

**Closed by Marius1311** 2023-09-13 12:26 UTC
Labels: bug

**Comment by hernandezvargash** [comment] 2023-11-06 12:44
Hi, I get the same error when following the tutorial in the "Visualize expression trends" section.
I tried excluding GATA1, and using `GAM` instead of `GAMR,` but no success. 
I have `rpy2` installed in my environment and `mgcv` installed in R.
Any other suggestions?
Thanks
